### ISSUE TITLE
Can't select the region for Digital Ocean

### ISSUE THREAD

**Issue by adrianexamcraft** [hypergrid-inc/dchq-io-issue-tracker#84]
Hi, 

I'm connected to my Cloud Provider (connection is established). I'm reciving the following error message when adding new Virtual Machine:

org.jclouds.rest.AuthorizationException: {"id":"unauthorized","message":"Unable to authenticate you."} and selecting region.

**Comment by hypergrid-inc** [comment]
Hey Adrian,

Are you sure that you've copied the correct API token from DigitalOcean in the Cloud Provider?

@intesar - is there anything else that Adrian needs to send us for further diagnostics?

Amjad

**Comment by adrianexamcraft** [comment]
Yes, the token was invalid, hover the massage was confirming that the connection was successful.
