### ISSUE TITLE
Run app with enough memory - does not work

### ISSUE THREAD

**Issue by meirka5** [hypergrid-inc/dchq-io-issue-tracker#87]
![image](https://cloud.githubusercontent.com/assets/4015911/26651645/079f0614-4656-11e7-8a2a-1fdb8f79728c.png)
As it could be seen - there is one machine with 2G free memory.

But, execution of the Run gives the following

![image](https://cloud.githubusercontent.com/assets/4015911/26651700/3ecb8d88-4656-11e7-9589-9f2bdd131053.png)

Please advise what to do, if it's not a Bug.

**Comment by hypergrid-inc** [comment]
Hey Meir,

You can click on Clusters and click Edit on Comp-East1. Under Advanced Configuration change Max Memory Policy to 400m or 500m. I hope this resolves the issue.

Amjad

**Comment by meirka5** [comment]
Hi Amjad, this solved my problem.
Still I have second issue with disabled links in the Cloud menu.

בתאריך 31 במאי 2017 23:32,‏ "HyperCloud" <notifications@github.com> כתב:

Hey Meir,

You can click on Clusters and click Edit on Comp-East1. Under Advanced
Configuration change Max Memory Policy to 400m or 500m. I hope this
resolves the issue.

Amjad

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hypergrid-inc/dchq-io-issue-tracker/issues/87#issuecomment-305308400>,
or mute the thread

**Comment by meirka5** [comment]
it works as well.
